name: Docker Build
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/v3-demo'
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: osjs
